/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CacheEntry } from "./CacheEntry";
import { CacheEntryCountArgs } from "./CacheEntryCountArgs";
import { CacheEntryFindManyArgs } from "./CacheEntryFindManyArgs";
import { CacheEntryFindUniqueArgs } from "./CacheEntryFindUniqueArgs";
import { DeleteCacheEntryArgs } from "./DeleteCacheEntryArgs";
import { CacheEntryService } from "../cacheEntry.service";
@graphql.Resolver(() => CacheEntry)
export class CacheEntryResolverBase {
  constructor(protected readonly service: CacheEntryService) {}

  async _cacheEntriesMeta(
    @graphql.Args() args: CacheEntryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CacheEntry])
  async cacheEntries(
    @graphql.Args() args: CacheEntryFindManyArgs
  ): Promise<CacheEntry[]> {
    return this.service.cacheEntries(args);
  }

  @graphql.Query(() => CacheEntry, { nullable: true })
  async cacheEntry(
    @graphql.Args() args: CacheEntryFindUniqueArgs
  ): Promise<CacheEntry | null> {
    const result = await this.service.cacheEntry(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CacheEntry)
  async deleteCacheEntry(
    @graphql.Args() args: DeleteCacheEntryArgs
  ): Promise<CacheEntry | null> {
    try {
      return await this.service.deleteCacheEntry(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
