/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, CacheEntry as PrismaCacheEntry } from "@prisma/client";

export class CacheEntryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CacheEntryCountArgs, "select">
  ): Promise<number> {
    return this.prisma.cacheEntry.count(args);
  }

  async cacheEntries(
    args: Prisma.CacheEntryFindManyArgs
  ): Promise<PrismaCacheEntry[]> {
    return this.prisma.cacheEntry.findMany(args);
  }
  async cacheEntry(
    args: Prisma.CacheEntryFindUniqueArgs
  ): Promise<PrismaCacheEntry | null> {
    return this.prisma.cacheEntry.findUnique(args);
  }
  async createCacheEntry(
    args: Prisma.CacheEntryCreateArgs
  ): Promise<PrismaCacheEntry> {
    return this.prisma.cacheEntry.create(args);
  }
  async updateCacheEntry(
    args: Prisma.CacheEntryUpdateArgs
  ): Promise<PrismaCacheEntry> {
    return this.prisma.cacheEntry.update(args);
  }
  async deleteCacheEntry(
    args: Prisma.CacheEntryDeleteArgs
  ): Promise<PrismaCacheEntry> {
    return this.prisma.cacheEntry.delete(args);
  }
}
