/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CacheEntryService } from "../cacheEntry.service";
import { CacheEntryCreateInput } from "./CacheEntryCreateInput";
import { CacheEntry } from "./CacheEntry";
import { CacheEntryFindManyArgs } from "./CacheEntryFindManyArgs";
import { CacheEntryWhereUniqueInput } from "./CacheEntryWhereUniqueInput";
import { CacheEntryUpdateInput } from "./CacheEntryUpdateInput";

export class CacheEntryControllerBase {
  constructor(protected readonly service: CacheEntryService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CacheEntry })
  async createCacheEntry(
    @common.Body() data: CacheEntryCreateInput
  ): Promise<CacheEntry> {
    return await this.service.createCacheEntry({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CacheEntry] })
  @ApiNestedQuery(CacheEntryFindManyArgs)
  async cacheEntries(@common.Req() request: Request): Promise<CacheEntry[]> {
    const args = plainToClass(CacheEntryFindManyArgs, request.query);
    return this.service.cacheEntries({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CacheEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async cacheEntry(
    @common.Param() params: CacheEntryWhereUniqueInput
  ): Promise<CacheEntry | null> {
    const result = await this.service.cacheEntry({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CacheEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCacheEntry(
    @common.Param() params: CacheEntryWhereUniqueInput,
    @common.Body() data: CacheEntryUpdateInput
  ): Promise<CacheEntry | null> {
    try {
      return await this.service.updateCacheEntry({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CacheEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCacheEntry(
    @common.Param() params: CacheEntryWhereUniqueInput
  ): Promise<CacheEntry | null> {
    try {
      return await this.service.deleteCacheEntry({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
